const SITE_URL = 'https://fullstack-forge.netlify.app';

// Keyword map: each entry is one page targeting one keyword
export const keywordMap = {
    home: {
        primary: 'website design for small business NZ',
        secondary: ['small business website NZ', 'websites that generate customers'],
        url: '/',
        title: 'Fullstack Forge — Websites That Generate Customers for Small Businesses',
    },
    webDesignChristchurch: {
        primary: 'web designer Christchurch',
        secondary: ['web developer Christchurch', 'website design Christchurch NZ', 'Christchurch web design'],
        url: '/web-design-christchurch',
        title: 'Web Design Christchurch — Fast, Affordable Websites That Get Results',
    },
    ecommerceWebsites: {
        primary: 'ecommerce website NZ',
        secondary: ['online store NZ', 'ecommerce websites New Zealand', 'build online store NZ'],
        url: '/ecommerce-websites-nz',
        title: 'E-Commerce Websites NZ — Online Stores Built to Sell',
    },
    websiteDesignSmallBusiness: {
        primary: 'affordable website design for small business NZ',
        secondary: ['small business website cost NZ', 'cheap website design NZ', 'website for small business NZ'],
        url: '/website-design-for-small-business',
        title: 'Website Design for Small Business NZ — Affordable, Fast, Effective',
    },
    affordableWebsites: {
        primary: 'affordable websites NZ',
        secondary: ['cheap websites NZ', 'budget website design New Zealand', 'low cost website NZ'],
        url: '/affordable-websites-nz',
        title: 'Affordable Websites NZ — Professional Sites From $1,000',
    },
};

// Blog categories for taxonomy
export const blogCategories = {
    pricing: { slug: 'pricing', label: 'Pricing & Cost' },
    'lead-generation': { slug: 'lead-generation', label: 'Lead Generation' },
    'web-design': { slug: 'web-design', label: 'Web Design' },
    seo: { slug: 'seo', label: 'SEO' },
    comparisons: { slug: 'comparisons', label: 'Comparisons' },
    'service-verticals': { slug: 'service-verticals', label: 'Industry Guides' },
};

// Content plan: blog articles targeting long-tail keywords
export const contentPlan = [
    {
        slug: 'how-much-does-a-website-cost-in-nz',
        keyword: 'website cost NZ',
        title: 'How Much Does a Website Cost in NZ? 2026 Pricing Guide',
        description: 'Complete NZ website pricing for 2026. Compare costs for small business, tradie, and ecommerce websites — from DIY to agency. Transparent pricing in NZD.',
        intent: 'commercial',
        category: 'pricing',
        linksTo: ['/affordable-websites-nz', '/website-design-for-small-business'],
        imageQuery: 'website design pricing',
        datePublished: '2025-01-15',
        readTime: 10,
    },
    {
        slug: 'best-website-design-for-small-businesses',
        keyword: 'best website design for small businesses',
        title: 'Best Website Design for Small Businesses in 2026',
        description: 'What makes a great small business website in NZ? Design principles, layout tips, trust signals, and real examples that turn visitors into customers.',
        intent: 'informational',
        category: 'web-design',
        linksTo: ['/website-design-for-small-business', '/'],
        imageQuery: 'modern website design',
        datePublished: '2025-01-20',
        readTime: 9,
    },
    {
        slug: 'do-small-businesses-need-a-website',
        keyword: 'do small businesses need a website 2026',
        title: 'Do Small Businesses Need a Website in 2026? (The Real Answer)',
        description: 'Website vs social media for NZ small businesses — ownership, credibility, lead capture, and the real ROI of having your own site.',
        intent: 'informational',
        category: 'web-design',
        linksTo: ['/affordable-websites-nz', '/'],
        imageQuery: 'small business owner laptop',
        datePublished: '2025-01-25',
        readTime: 8,
    },
    {
        slug: 'how-to-get-customers-from-your-website',
        keyword: 'how to get customers from website',
        title: 'How to Get Customers From Your Website: The Complete Beginner\'s Framework',
        description: 'The step-by-step journey from website visitor to paying customer — traffic, trust, conversion, and follow-up explained for NZ small businesses.',
        intent: 'informational',
        category: 'lead-generation',
        linksTo: ['/', '/website-design-for-small-business'],
        imageQuery: 'digital marketing strategy',
        datePublished: '2025-02-01',
        readTime: 9,
    },
    {
        slug: 'website-for-cleaning-business-nz',
        keyword: 'website for cleaning business NZ',
        title: 'Website for Cleaning Business NZ — Get More Bookings Online',
        description: 'What NZ cleaning businesses need on their website to generate consistent bookings — local SEO, trust signals, quote forms, and real examples.',
        intent: 'commercial',
        category: 'service-verticals',
        linksTo: ['/affordable-websites-nz', '/web-design-christchurch'],
        imageQuery: 'professional cleaning service',
        datePublished: '2025-02-05',
        readTime: 9,
    },
    {
        slug: 'website-for-tradies-nz',
        keyword: 'tradie website New Zealand',
        title: 'Tradie Website NZ: How Auckland Tradies Get More Jobs Online in 2026',
        description: 'The complete guide to tradie websites in New Zealand. Learn how plumbers, electricians, and builders use web design and local SEO to get more leads and higher-paying jobs.',
        intent: 'commercial',
        category: 'service-verticals',
        linksTo: ['/affordable-websites-nz', '/website-design-for-small-business'],
        imageQuery: 'construction worker tools',
        datePublished: '2025-02-10',
        readTime: 9,
    },
    {
        slug: 'seo-for-small-business-nz',
        keyword: 'SEO for small business NZ',
        title: 'SEO for Small Business NZ — A Beginner\'s Guide to Ranking on Google',
        description: 'The complete beginner\'s guide to SEO for NZ small businesses — local search, Google Business Profile, on-page basics, and a practical checklist.',
        intent: 'informational',
        category: 'seo',
        linksTo: ['/', '/web-design-christchurch'],
        imageQuery: 'search engine optimization',
        datePublished: '2025-02-15',
        readTime: 10,
    },
    {
        slug: 'diy-vs-professional-website',
        keyword: 'DIY website vs professional website',
        title: 'DIY Website vs Professional Website — Which Is Right for Your Business?',
        description: 'Should you build your own website or hire a pro? An honest comparison of time, cost, ROI, and long-term value for NZ small businesses.',
        intent: 'informational',
        category: 'comparisons',
        linksTo: ['/affordable-websites-nz', '/website-design-for-small-business'],
        imageQuery: 'web developer coding laptop',
        datePublished: '2025-02-20',
        readTime: 8,
    },
    {
        slug: 'best-website-builder-for-small-business-nz',
        keyword: 'best website builder for small business NZ',
        title: 'Best Website Builder for Small Business NZ (2026 Comparison)',
        description: 'Wix vs Squarespace vs Shopify vs WordPress vs custom — which platform is best for NZ small businesses? Features, costs, and recommendations.',
        intent: 'informational',
        category: 'comparisons',
        linksTo: ['/ecommerce-websites-nz', '/affordable-websites-nz'],
        imageQuery: 'website builder platform',
        datePublished: '2025-02-25',
        readTime: 9,
    },
    {
        slug: 'how-to-get-more-leads-from-your-website',
        keyword: 'how to get more leads from website',
        title: 'How to Get More Leads From Your Website in 2026 (Without Paying for Ads)',
        description: 'Your website gets traffic but no enquiries? Here are 10 proven lead generation tactics NZ small businesses are using right now to turn visitors into paying customers.',
        intent: 'informational',
        category: 'lead-generation',
        linksTo: ['/', '/website-design-for-small-business', '/affordable-websites-nz', '/web-design-christchurch', '/ecommerce-websites-nz'],
        imageQuery: 'lead generation business growth',
        datePublished: '2025-03-01',
        readTime: 12,
    },
    {
        slug: 'how-much-does-a-tradie-website-cost-in-nz',
        keyword: 'tradie website cost NZ',
        title: 'How Much Does a Tradie Website Cost in NZ? 2026 Pricing Guide',
        description: 'What does a tradie website cost in New Zealand? Compare DIY, freelancer, and specialist pricing for plumbers, electricians, builders, and other tradies in NZ.',
        intent: 'commercial',
        category: 'pricing',
        linksTo: ['/affordable-websites-nz', '/website-design-for-small-business'],
        imageQuery: 'tradesman tools construction',
        datePublished: '2026-04-04',
        readTime: 11,
    },
    {
        slug: 'local-seo-for-tradies-nz',
        keyword: 'local SEO for tradies NZ',
        title: 'Local SEO for Tradies NZ: How to Rank in Your City and Get More Jobs',
        description: 'Learn how local SEO for tradies in NZ works. Get found in Google for searches like plumber Auckland, electrician Christchurch, and builder near me.',
        intent: 'informational',
        category: 'seo',
        linksTo: ['/blog/website-for-tradies-nz', '/blog/seo-for-small-business-nz', '/affordable-websites-nz'],
        imageQuery: 'local seo tradie business',
        datePublished: '2026-04-04',
        readTime: 11,
    },
    {
        slug: 'website-vs-facebook-page-nz-small-business',
        keyword: 'website vs Facebook page NZ small business',
        title: 'Website vs Facebook Page for NZ Small Businesses: Which Do You Really Need?',
        description: 'Should a NZ small business rely on Facebook or build a website? Here\'s the real difference in trust, control, SEO, and lead generation.',
        intent: 'informational',
        category: 'comparisons',
        linksTo: ['/website-design-for-small-business', '/blog/do-small-businesses-need-a-website', '/blog/how-to-get-more-leads-from-your-website'],
        imageQuery: 'small business website social media',
        datePublished: '2026-04-04',
        readTime: 10,
    },
    {
        slug: 'cleaning-business-seo-nz',
        keyword: 'cleaning business SEO NZ',
        title: 'Cleaning Business SEO NZ: How to Get More Bookings From Google',
        description: 'Learn how cleaning businesses in New Zealand can use SEO to get more bookings from Google, rank locally, and turn website traffic into steady enquiries.',
        intent: 'informational',
        category: 'seo',
        linksTo: ['/blog/website-for-cleaning-business-nz', '/blog/seo-for-small-business-nz', '/affordable-websites-nz'],
        imageQuery: 'cleaning business seo',
        datePublished: '2026-04-04',
        readTime: 11,
    },
    {
        slug: 'how-to-get-more-quote-requests-from-your-website',
        keyword: 'how to get more quote requests from your website',
        title: 'How to Get More Quote Requests From Your Website',
        description: 'Learn how to get more quote requests from your website with better CTAs, trust signals, forms, and conversion-focused design for NZ small businesses.',
        intent: 'informational',
        category: 'lead-generation',
        linksTo: ['/blog/how-to-get-more-leads-from-your-website', '/blog/how-much-does-a-website-cost-in-nz', '/website-design-for-small-business'],
        imageQuery: 'website quote request conversion',
        datePublished: '2026-04-04',
        readTime: 11,
    },
    {
        slug: 'best-homepage-layout-for-small-business-website',
        keyword: 'best homepage layout for small business website',
        title: 'Best Homepage Layout for a Small Business Website',
        description: 'Learn what the best homepage layout for a small business website looks like, including hero section, trust signals, service blocks, CTAs, and local SEO structure.',
        intent: 'informational',
        category: 'web-design',
        linksTo: ['/blog/best-website-design-for-small-businesses', '/blog/how-to-get-more-leads-from-your-website', '/website-design-for-small-business'],
        imageQuery: 'small business homepage layout',
        datePublished: '2026-04-04',
        readTime: 11,
    },
    {
        slug: 'small-business-website-checklist-nz',
        keyword: 'small business website checklist NZ',
        title: 'Small Business Website Checklist NZ: What Your Website Needs to Convert',
        description: 'Use this small business website checklist for NZ companies to make sure your site is clear, trustworthy, mobile-friendly, and built to generate enquiries.',
        intent: 'informational',
        category: 'web-design',
        linksTo: ['/website-design-for-small-business', '/blog/how-to-get-more-leads-from-your-website', '/blog/seo-for-small-business-nz'],
        imageQuery: 'small business website checklist',
        datePublished: '2026-04-04',
        readTime: 11,
    },
    {
        slug: 'common-website-mistakes-nz-small-businesses',
        keyword: 'common website mistakes NZ small businesses',
        title: 'Common Website Mistakes NZ Small Businesses Make',
        description: 'Avoid the most common website mistakes NZ small businesses make — from unclear messaging and missing CTAs to slow mobile load times and weak trust signals.',
        intent: 'informational',
        category: 'web-design',
        linksTo: ['/website-design-for-small-business', '/blog/best-homepage-layout-for-small-business-website', '/blog/seo-for-small-business-nz'],
        imageQuery: 'small business website mistakes',
        datePublished: '2026-04-04',
        readTime: 11,
    },
    {
        slug: 'how-long-does-seo-take-for-small-business-in-nz',
        keyword: 'how long does SEO take for small business in NZ',
        title: 'How Long Does SEO Take for a Small Business in NZ?',
        description: 'Find out how long SEO takes for a small business in NZ, what affects ranking speed, and what to realistically expect month by month from local SEO efforts.',
        intent: 'informational',
        category: 'seo',
        linksTo: ['/blog/seo-for-small-business-nz', '/blog/how-to-get-more-leads-from-your-website', '/website-design-for-small-business'],
        imageQuery: 'seo timeline small business',
        datePublished: '2026-04-04',
        readTime: 11,
    },
    {
        slug: 'what-pages-should-a-small-business-website-have',
        keyword: 'what pages should a small business website have',
        title: 'What Pages Should a Small Business Website Have?',
        description: 'Learn what pages a small business website should have in NZ, including homepage, services, pricing, trust pages, and contact flow that actually helps generate enquiries.',
        intent: 'informational',
        category: 'web-design',
        linksTo: ['/website-design-for-small-business', '/blog/best-homepage-layout-for-small-business-website', '/blog/how-to-get-more-quote-requests-from-your-website'],
        imageQuery: 'small business website pages',
        datePublished: '2026-04-04',
        readTime: 11,
    },
];

export { SITE_URL };
